[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
edition = "2018"
name = "moarsql"
version = "0.1.0"

[dependencies]
failure = "0.1.5"
itertools = "0.8.0"
serde = "1.0.91"
serde_derive = "1.0.91"
structopt = "0.2.15"
toml = "0.5.0"
